//! Tests for map column support
//!
//! Tests reading and writing Parquet files with map columns.

const std = @import("std");
const io = std.testing.io;
const parquet = @import("../lib.zig");

const Value = parquet.Value;
const Writer = parquet.Writer;
const ColumnDef = parquet.ColumnDef;
const Optional = parquet.Optional;
const WriterMapEntry = @import("../core/map_encoder.zig").MapEntry;

// =============================================================================
// Read tests
// =============================================================================

test "read map_string_int.parquet" {
    const allocator = std.testing.allocator;

    // Open the file generated by PyArrow
    const file = std.Io.Dir.cwd().openFile(io, "../test-files-arrow/nested/map_string_int.parquet", .{}) catch |err| {
        std.debug.print("Skipping test - file not found: {}\n", .{err});
        return;
    };
    defer file.close(io);

    var reader = try parquet.openFileDynamic(allocator, file, io, .{});
    defer reader.deinit();

    // File has 5 rows:
    // Row 0: {"a": 1, "b": 2}
    // Row 1: {"c": 3}
    // Row 2: {} (empty map)
    // Row 3: null
    // Row 4: {"d": 4, "e": 5, "f": 6}

    const rows = try reader.readAllRows(0);
    defer {
        for (rows) |row| row.deinit();
        allocator.free(rows);
    }

    try std.testing.expectEqual(@as(usize, 5), rows.len);

    // Row 0: {"a": 1, "b": 2}
    const map0 = rows[0].getColumn(0).?;
    switch (map0) {
        .map_val => |entries| {
            try std.testing.expectEqual(@as(usize, 2), entries.len);
            try std.testing.expectEqualStrings("a", entries[0].key.asBytes().?);
            try std.testing.expectEqual(@as(i32, 1), entries[0].value.asInt32().?);
            try std.testing.expectEqualStrings("b", entries[1].key.asBytes().?);
            try std.testing.expectEqual(@as(i32, 2), entries[1].value.asInt32().?);
        },
        else => return error.TestUnexpectedResult,
    }

    // Row 1: {"c": 3}
    const map1 = rows[1].getColumn(0).?;
    switch (map1) {
        .map_val => |entries| {
            try std.testing.expectEqual(@as(usize, 1), entries.len);
            try std.testing.expectEqualStrings("c", entries[0].key.asBytes().?);
            try std.testing.expectEqual(@as(i32, 3), entries[0].value.asInt32().?);
        },
        else => return error.TestUnexpectedResult,
    }

    // Row 2: {} (empty map)
    const map2 = rows[2].getColumn(0).?;
    switch (map2) {
        .map_val => |entries| {
            try std.testing.expectEqual(@as(usize, 0), entries.len);
        },
        else => return error.TestUnexpectedResult,
    }

    // Row 3: null
    try std.testing.expect(rows[3].getColumn(0).?.isNull());

    // Row 4: {"d": 4, "e": 5, "f": 6}
    const map4 = rows[4].getColumn(0).?;
    switch (map4) {
        .map_val => |entries| {
            try std.testing.expectEqual(@as(usize, 3), entries.len);
            try std.testing.expectEqualStrings("d", entries[0].key.asBytes().?);
            try std.testing.expectEqual(@as(i32, 4), entries[0].value.asInt32().?);
            try std.testing.expectEqualStrings("e", entries[1].key.asBytes().?);
            try std.testing.expectEqual(@as(i32, 5), entries[1].value.asInt32().?);
            try std.testing.expectEqualStrings("f", entries[2].key.asBytes().?);
            try std.testing.expectEqual(@as(i32, 6), entries[2].value.asInt32().?);
        },
        else => return error.TestUnexpectedResult,
    }
}

// =============================================================================
// Round-trip tests
// =============================================================================

test "write and read simple map" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_simple.parquet";

    // Write a parquet file with a map column
    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        // Define columns
        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt32("attributes", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        // Map data: [{a: 1, b: 2}, {c: 3}]
        const entries0 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "a", .value = .{ .value = 1 } },
            .{ .key = "b", .value = .{ .value = 2 } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "c", .value = .{ .value = 3 } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i32)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
        };

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read it back
    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 2), rows.len);

        // Row 0: {a: 1, b: 2}
        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("a", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(i32, 1), entries[0].value.asInt32().?);
                try std.testing.expectEqualStrings("b", entries[1].key.asBytes().?);
                try std.testing.expectEqual(@as(i32, 2), entries[1].value.asInt32().?);
            },
            else => return error.TestUnexpectedResult,
        }

        // Row 1: {c: 3}
        const map1 = rows[1].getColumn(0).?;
        switch (map1) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 1), entries.len);
                try std.testing.expectEqualStrings("c", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(i32, 3), entries[0].value.asInt32().?);
            },
            else => return error.TestUnexpectedResult,
        }
    }
}

test "write and read map with null values" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_null_values.parquet";

    // Write
    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt32("data", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        // Map data: [{a: 1, b: null, c: 3}]
        const entries0 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "a", .value = .{ .value = 1 } },
            .{ .key = "b", .value = .{ .null_value = {} } },
            .{ .key = "c", .value = .{ .value = 3 } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i32)){
            .{ .value = &entries0 },
        };

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read
    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 1), rows.len);

        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 3), entries.len);

                try std.testing.expectEqualStrings("a", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(i32, 1), entries[0].value.asInt32().?);

                try std.testing.expectEqualStrings("b", entries[1].key.asBytes().?);
                try std.testing.expect(entries[1].value.isNull());

                try std.testing.expectEqualStrings("c", entries[2].key.asBytes().?);
                try std.testing.expectEqual(@as(i32, 3), entries[2].value.asInt32().?);
            },
            else => return error.TestUnexpectedResult,
        }
    }
}

test "write and read map with null and empty maps" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_null_empty.parquet";

    // Write
    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt32("data", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        // Map data: [{a: 1}, null, {}]
        const entries0 = [_]WriterMapEntry([]const u8, i32){
            .{ .key = "a", .value = .{ .value = 1 } },
        };
        const entries2 = [_]WriterMapEntry([]const u8, i32){};
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i32)){
            .{ .value = &entries0 },
            .{ .null_value = {} },
            .{ .value = &entries2 },
        };

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read
    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 3), rows.len);

        // Row 0: {a: 1}
        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 1), entries.len);
            },
            else => return error.TestUnexpectedResult,
        }

        // Row 1: null
        try std.testing.expect(rows[1].getColumn(0).?.isNull());

        // Row 2: {} (empty map)
        const map2 = rows[2].getColumn(0).?;
        switch (map2) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 0), entries.len);
            },
            else => return error.TestUnexpectedResult,
        }
    }
}

test "write and read large map column (multi-page accumulator test)" {
    // This test verifies that the map column reader correctly accumulates values
    // when processing large datasets. While this test may fit in a single page
    // when written by zig-parquet, the accumulator-based reading logic in
    // decodeMapColumn is essential for reading multi-page maps from other writers
    // (e.g., Spark, PyArrow with large datasets).
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "large_map.parquet";

    // Write phase: create many rows with varying map sizes
    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{ .read = true });
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.map("data", .byte_array, .int32, true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        // Generate 100 rows with varying map sizes (0-10 entries each)
        // Total ~500 key-value pairs to exercise accumulator logic
        var maps: [100]Optional([]const WriterMapEntry([]const u8, i32)) = undefined;
        var all_entries: [1000]WriterMapEntry([]const u8, i32) = undefined;
        var entry_idx: usize = 0;

        // Pre-generate all keys (we need stable string references)
        var keys: [1000][8]u8 = undefined;
        for (0..1000) |i| {
            const key_slice = std.fmt.bufPrint(&keys[i], "key{d:04}", .{i}) catch unreachable;
            _ = key_slice;
        }

        for (0..100) |row| {
            const num_entries = row % 11; // 0-10 entries per row
            if (num_entries == 0) {
                // Empty map (not null)
                maps[row] = .{ .value = &[_]WriterMapEntry([]const u8, i32){} };
            } else {
                const start = entry_idx;
                for (0..num_entries) |j| {
                    all_entries[entry_idx] = .{
                        .key = keys[entry_idx][0..std.fmt.count("key{d:04}", .{entry_idx})],
                        .value = .{ .value = @intCast(row * 100 + j) },
                    };
                    entry_idx += 1;
                }
                maps[row] = .{ .value = all_entries[start..entry_idx] };
            }
        }

        try writer.writeMapColumnStringInt32(0, &maps);
        try writer.close();
    }

    // Read phase: verify all data
    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 100), rows.len);

        // Verify a sample of rows
        // Row 0: 0 entries (empty)
        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 0), entries.len);
            },
            else => return error.TestUnexpectedResult,
        }

        // Row 5: 5 entries
        const map5 = rows[5].getColumn(0).?;
        switch (map5) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 5), entries.len);
            },
            else => return error.TestUnexpectedResult,
        }

        // Row 10: 10 entries
        const map10 = rows[10].getColumn(0).?;
        switch (map10) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 10), entries.len);
            },
            else => return error.TestUnexpectedResult,
        }

        // Verify all row entry counts match expected pattern
        for (rows, 0..) |row, row_idx| {
            const expected_entries = row_idx % 11;
            const map = row.getColumn(0).?;
            switch (map) {
                .map_val => |entries| {
                    try std.testing.expectEqual(expected_entries, entries.len);
                },
                else => return error.TestUnexpectedResult,
            }
        }
    }

}

// =============================================================================
// New type combination round-trip tests
// =============================================================================

test "round-trip map string-to-f64" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_f64.parquet";

    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapStringFloat64("scores", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, f64){
            .{ .key = "math", .value = .{ .value = 95.5 } },
            .{ .key = "science", .value = .{ .value = 88.25 } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, f64){
            .{ .key = "english", .value = .{ .value = 72.0 } },
            .{ .key = "history", .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, f64)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
            .{ .null_value = {} },
        };

        try writer.writeMapColumn([]const u8, f64, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 3), rows.len);

        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("math", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(f64, 95.5), entries[0].value.asDouble().?);
                try std.testing.expectEqualStrings("science", entries[1].key.asBytes().?);
                try std.testing.expectEqual(@as(f64, 88.25), entries[1].value.asDouble().?);
            },
            else => return error.TestUnexpectedResult,
        }

        const map1 = rows[1].getColumn(0).?;
        switch (map1) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("english", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(f64, 72.0), entries[0].value.asDouble().?);
                try std.testing.expectEqualStrings("history", entries[1].key.asBytes().?);
                try std.testing.expect(entries[1].value.isNull());
            },
            else => return error.TestUnexpectedResult,
        }

        try std.testing.expect(rows[2].getColumn(0).?.isNull());
    }
}

test "round-trip map string-to-bool" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_bool.parquet";

    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapStringBool("flags", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, bool){
            .{ .key = "active", .value = .{ .value = true } },
            .{ .key = "verified", .value = .{ .value = false } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, bool){
            .{ .key = "admin", .value = .{ .value = true } },
            .{ .key = "deleted", .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, bool)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
        };

        try writer.writeMapColumn([]const u8, bool, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 2), rows.len);

        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("active", entries[0].key.asBytes().?);
                try std.testing.expectEqual(true, entries[0].value.asBool().?);
                try std.testing.expectEqualStrings("verified", entries[1].key.asBytes().?);
                try std.testing.expectEqual(false, entries[1].value.asBool().?);
            },
            else => return error.TestUnexpectedResult,
        }

        const map1 = rows[1].getColumn(0).?;
        switch (map1) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("admin", entries[0].key.asBytes().?);
                try std.testing.expectEqual(true, entries[0].value.asBool().?);
                try std.testing.expectEqualStrings("deleted", entries[1].key.asBytes().?);
                try std.testing.expect(entries[1].value.isNull());
            },
            else => return error.TestUnexpectedResult,
        }
    }
}

test "round-trip map i32-to-string" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_i32_string.parquet";

    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapInt32String("labels", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry(i32, []const u8){
            .{ .key = 1, .value = .{ .value = "one" } },
            .{ .key = 2, .value = .{ .value = "two" } },
        };
        const entries1 = [_]WriterMapEntry(i32, []const u8){
            .{ .key = 100, .value = .{ .value = "hundred" } },
            .{ .key = 200, .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry(i32, []const u8)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
            .{ .null_value = {} },
        };

        try writer.writeMapColumn(i32, []const u8, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 3), rows.len);

        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqual(@as(i32, 1), entries[0].key.asInt32().?);
                try std.testing.expectEqualStrings("one", entries[0].value.asBytes().?);
                try std.testing.expectEqual(@as(i32, 2), entries[1].key.asInt32().?);
                try std.testing.expectEqualStrings("two", entries[1].value.asBytes().?);
            },
            else => return error.TestUnexpectedResult,
        }

        const map1 = rows[1].getColumn(0).?;
        switch (map1) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqual(@as(i32, 100), entries[0].key.asInt32().?);
                try std.testing.expectEqualStrings("hundred", entries[0].value.asBytes().?);
                try std.testing.expectEqual(@as(i32, 200), entries[1].key.asInt32().?);
                try std.testing.expect(entries[1].value.isNull());
            },
            else => return error.TestUnexpectedResult,
        }

        try std.testing.expect(rows[2].getColumn(0).?.isNull());
    }
}

test "round-trip map string-to-i64" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_i64.parquet";

    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapStringInt64("timestamps", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, i64){
            .{ .key = "created", .value = .{ .value = 1700000000000 } },
            .{ .key = "updated", .value = .{ .value = 1700001000000 } },
        };
        const entries1 = [_]WriterMapEntry([]const u8, i64){
            .{ .key = "deleted", .value = .{ .null_value = {} } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, i64)){
            .{ .value = &entries0 },
            .{ .value = &entries1 },
        };

        try writer.writeMapColumn([]const u8, i64, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 2), rows.len);

        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("created", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(i64, 1700000000000), entries[0].value.asInt64().?);
                try std.testing.expectEqualStrings("updated", entries[1].key.asBytes().?);
                try std.testing.expectEqual(@as(i64, 1700001000000), entries[1].value.asInt64().?);
            },
            else => return error.TestUnexpectedResult,
        }

        const map1 = rows[1].getColumn(0).?;
        switch (map1) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 1), entries.len);
                try std.testing.expectEqualStrings("deleted", entries[0].key.asBytes().?);
                try std.testing.expect(entries[0].value.isNull());
            },
            else => return error.TestUnexpectedResult,
        }
    }
}

test "round-trip map string-to-f32" {
    const allocator = std.testing.allocator;

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const file_path = "map_string_f32.parquet";

    {
        const file = try tmp_dir.dir.createFile(io, file_path, .{});
        defer file.close(io);

        const columns = [_]ColumnDef{
            ColumnDef.mapStringFloat32("weights", true),
        };

        var writer = try parquet.writeToFile(allocator, file, io, &columns);
        defer writer.deinit();

        const entries0 = [_]WriterMapEntry([]const u8, f32){
            .{ .key = "alpha", .value = .{ .value = 0.5 } },
            .{ .key = "beta", .value = .{ .value = 1.25 } },
        };
        const maps = [_]Optional([]const WriterMapEntry([]const u8, f32)){
            .{ .value = &entries0 },
            .{ .null_value = {} },
        };

        try writer.writeMapColumn([]const u8, f32, 0, &maps);
        try writer.close();
    }

    {
        const file = try tmp_dir.dir.openFile(io, file_path, .{});
        defer file.close(io);

        var reader = try parquet.openFileDynamic(allocator, file, io, .{});
        defer reader.deinit();

        const rows = try reader.readAllRows(0);
        defer {
            for (rows) |row| row.deinit();
            allocator.free(rows);
        }

        try std.testing.expectEqual(@as(usize, 2), rows.len);

        const map0 = rows[0].getColumn(0).?;
        switch (map0) {
            .map_val => |entries| {
                try std.testing.expectEqual(@as(usize, 2), entries.len);
                try std.testing.expectEqualStrings("alpha", entries[0].key.asBytes().?);
                try std.testing.expectEqual(@as(f32, 0.5), entries[0].value.asFloat().?);
                try std.testing.expectEqualStrings("beta", entries[1].key.asBytes().?);
                try std.testing.expectEqual(@as(f32, 1.25), entries[1].value.asFloat().?);
            },
            else => return error.TestUnexpectedResult,
        }

        try std.testing.expect(rows[1].getColumn(0).?.isNull());
    }
}
