/**
 * @file codegen.c
 * @brief Codegen command dispatcher — routes to codegen_read / codegen_write.
 */

#include "cli.h"
#include <stdio.h>
#include <string.h>

/* Generate a template reader when no -f is provided */
static int codegen_read_template(FILE* out, const codegen_opts_t* opts,
                                 codegen_hints_t* hints) {
    int line = 1;

    /* Count newlines in a string */
    #define NL(s) do { for (const char* _p = (s); *_p; _p++) if (*_p == '\n') line++; fputs((s), out); } while(0)

    NL("/*\n"
       " * Auto-generated by: carquet codegen --read (template)\n"
       " *\n"
       " * No -f/--file was specified. Edit the schema below and set\n"
       " * DEFAULT_FILE to match your Parquet file.\n"
       " */\n\n"
       "#include <stdio.h>\n"
       "#include <stdlib.h>\n"
       "#include <inttypes.h>\n"
       "#include <carquet/carquet.h>\n\n");

    hints->default_file_line = line + 1;
    NL("#define DEFAULT_FILE \"/path/to/file.parquet\"  /* <-- edit this */\n\n");

    NL("/* Edit this schema to match your Parquet file.\n"
       " * Use 'carquet schema <file>' to see the schema of a real file. */\n"
       "#define NUM_COLUMNS 3\n\n");

    hints->process_batch_line = line + 7;
    NL("static void process_batch(\n"
       "    int32_t row_group,\n"
       "    int64_t batch_offset,\n"
       "    int64_t count,\n"
       "    const int64_t* col0,      /* column 0: edit type and name */\n"
       "    const double* col1,       /* column 1: edit type and name */\n"
       "    const int32_t* col2)      /* column 2: edit type and name */\n"
       "{\n"
       "    /* TODO: implement your processing logic here */\n"
       "    (void)row_group; (void)batch_offset;\n"
       "    for (int64_t i = 0; i < count; i++) {\n"
       "        printf(\"%\" PRId64 \"\\t%g\\t%\" PRId32 \"\\n\",\n"
       "               col0[i], col1[i], col2[i]);\n"
       "    }\n"
       "}\n\n");

    int batch_size = opts->batch_size;
    fprintf(out,
        "int main(int argc, char** argv) {\n"
        "    const char* path = (argc >= 2) ? argv[1] : DEFAULT_FILE;\n\n"
        "    carquet_error_t err = CARQUET_ERROR_INIT;\n"
        "    carquet_reader_t* reader = carquet_reader_open(path, NULL, &err);\n"
        "    if (!reader) {\n"
        "        fprintf(stderr, \"Error: %%s\\n\", err.message);\n"
        "        return 1;\n"
        "    }\n\n"
        "    int64_t total = carquet_reader_num_rows(reader);\n"
        "    int32_t num_rgs = carquet_reader_num_row_groups(reader);\n"
        "    printf(\"Reading %%\" PRId64 \" rows\\n\", total);\n\n"
        "    for (int32_t rg = 0; rg < num_rgs; rg++) {\n"
        "        /* Edit: match buffer types to your schema */\n"
        "        int64_t  col0_buf[%d];\n"
        "        double   col1_buf[%d];\n"
        "        int32_t  col2_buf[%d];\n\n"
        "        carquet_column_reader_t* c0 = carquet_reader_get_column(reader, rg, 0, &err);\n"
        "        carquet_column_reader_t* c1 = carquet_reader_get_column(reader, rg, 1, &err);\n"
        "        carquet_column_reader_t* c2 = carquet_reader_get_column(reader, rg, 2, &err);\n"
        "        if (!c0 || !c1 || !c2) {\n"
        "            fprintf(stderr, \"Error: %%s\\n\", err.message);\n"
        "            carquet_reader_close(reader);\n"
        "            return 1;\n"
        "        }\n\n"
        "        int64_t batch_offset = 0;\n"
        "        for (;;) {\n"
        "            int64_t count = carquet_column_read_batch(c0, col0_buf, %d, NULL, NULL);\n"
        "            if (count <= 0) break;\n"
        "            (void)carquet_column_read_batch(c1, col1_buf, count, NULL, NULL);\n"
        "            (void)carquet_column_read_batch(c2, col2_buf, count, NULL, NULL);\n"
        "            process_batch(rg, batch_offset, count, col0_buf, col1_buf, col2_buf);\n"
        "            batch_offset += count;\n"
        "        }\n\n"
        "        carquet_column_reader_free(c0);\n"
        "        carquet_column_reader_free(c1);\n"
        "        carquet_column_reader_free(c2);\n"
        "    }\n\n"
        "    carquet_reader_close(reader);\n"
        "    printf(\"Done.\\n\");\n"
        "    return 0;\n"
        "}\n",
        batch_size, batch_size, batch_size, batch_size);

    #undef NL
    return 0;
}

int cmd_codegen(const codegen_opts_t* opts) {
    if (opts->mode == 1)
        return cmd_codegen_write(opts);

    /* mode == 0 (read) */
    FILE* out = stdout;
    if (opts->output_path) {
        out = fopen(opts->output_path, "w");
        if (!out) {
            fprintf(stderr, "error: cannot open output file '%s'\n", opts->output_path);
            return 1;
        }
    }

    codegen_hints_t hints = {0};
    int ret;

    if (opts->input_path) {
        /* File provided: inspect schema and generate tailored code */
        carquet_error_t err = CARQUET_ERROR_INIT;
        carquet_reader_t* reader = carquet_reader_open(opts->input_path, NULL, &err);
        if (!reader) {
            fprintf(stderr, "error: %s\n", err.message);
            if (opts->output_path) fclose(out);
            return 1;
        }
        ret = cmd_codegen_read(out, reader, opts, &hints);
        carquet_reader_close(reader);
    } else {
        /* No file: generate editable template */
        ret = codegen_read_template(out, opts, &hints);
    }

    if (opts->output_path) {
        fclose(out);
        if (ret == 0) {
            fprintf(stderr, "Generated: %s\n", opts->output_path);
            if (hints.build_line[0])
                fprintf(stderr, "Compile:   %s\n", hints.build_line);
            if (!opts->input_path) {
                /* Template mode — guide the user through all edits */
                fprintf(stderr, "\n");
                fprintf(stderr, "This is a template. To make it work:\n");
                if (hints.default_file_line > 0)
                    fprintf(stderr, "  1. Set your parquet file path at line %d (DEFAULT_FILE)\n",
                            hints.default_file_line);
                if (hints.process_batch_line > 0)
                    fprintf(stderr, "  2. Edit the example schema (3 columns: INT64, DOUBLE, INT32)\n"
                            "     to match your file. Use 'carquet schema <file>' to discover it.\n"
                            "     Update column types, names, and count in process_batch() at line %d,\n"
                            "     buffers and column readers in main().\n",
                            hints.process_batch_line);
                fprintf(stderr, "\nTip: use 'carquet codegen -f <file>' to skip all manual editing.\n");
            } else if (opts->skeleton && hints.process_batch_line > 0) {
                fprintf(stderr, "Note:      edit process_batch() body at line %d\n",
                        hints.process_batch_line);
            }
        }
    }

    return ret;
}
